import 'package:flutter/material.dart';
import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'ar': {
          'start1': 'أفضل تجربة لشراء',
          'start2': 'الطعام بسرعة',
          'start3': 'انشاء حساب',
          'start4': 'تسجيل الدخول',
          'wellcome': 'مرحبا بك مرة أخرى',
          'enterAccount': 'ادخل الحساب الخاص بك لاستخدام التطبيق',
          'email': 'البريد الالكتروني',
          'enterEmail': 'ادخل البريد الالكتروني الخاص  بك',
          'password': 'كلمة المرور',
          'enterPassword': 'ادخل كلمة السر الخاصة بك',
          'rememberme': 'تذكرني ',
          'forgetpassword': 'نسيت كلمة المرور',
          'login': 'تسجيل الدخول',
          'donthaveaccount': 'ليس لديك حساب ؟',
          'signup': 'انشئ حساب',
          'CreateAccount': 'أنشأ حساب جديد',
          'Name*': 'الاسم',
          'EnterName': 'ادخل اسمك',
          'enterRegisterEmail': 'ادخل حسابك الالكتروني',
          'we will send': 'سوف نرسل لك كود التحقق الى حسابك\nالالكتروني',
          'Next': 'التالي',
          'we have send': 'لقد ارسلنا رمز التحقق الى \nبريدك الالكتروني',
          'Vertification': 'رمز التحقق',
          'entervertificationcode': 'ادخل رمز التحقق من فضلك',
          'Change password': 'تغيير كلمة المرور',
          'Please enter new password': 'ادخل كلمة مرور جديدة من فضلك',
          'Enter new password': 'ادخل كلمة مرور جديدة',
          'Re-enter your password': 'اعد ادخال كلمة المرور',
          'Finish': 'انتهينا',
          'Home': 'الصفحة الرئيسية',
          'Search': 'البحث',
          'Favorite': 'المفضلة',
          'Profile': 'الملف الشخصي',
          'Change Language': 'تغيير اللغة ',
          'Location': 'الموقع',
          'Tartous/Syria': 'سوريا/طرطوس',
          'Hie Mister': 'مرحبا يا سيدي',
          'You have 13 discount ticket!': 'لديك 13 تذكرة خضم',
          'Categories': 'التصنيفات',
          'Best Sellings': 'الأكثر مبيع',
          'See all product': 'رؤية كل المنتجات',
          'Fast Food': 'وجبات سريعة',
          'Healthy Food': 'وجبات صحية',
          'Sweet Food': 'حلويات',
          'Meat': 'لحم',
          'Bread': 'خبز',
          'Pizza': 'بيتزا',
          'Fried Chicken': 'فروج مقلي',
          'Dominoz Pizza': 'دومينوز بيتزا',
          'Abo Ali resturant': 'مطعم ابو علي',
          'Cheese Burger': 'برغر بالجبن',
          'Makdonald': 'ماكدونالد',
          'Fruit Salad': 'سلطة فواكه',
          'Fruty': 'فروتي',
          'Donut': 'دونات',
          'Donti': 'دونتي',
          'Fried Potato': 'بطاطا مقلية',
          'Cart': 'سلة المشتريات',
          'Total Price': 'السعر الكلي',
          'Check Out': 'سحب',
          'Payment': 'الدفع',
          'Confirm': 'تأكيد',
          'All Product': 'جميع المنتجات',
          'search....': 'بحث',
          'Remove all': 'ازالة الكل',
          'Great!': 'عظيم',
          'Payment Success': 'تمت عملية الدفع بنجاح',
          'from bank': 'من بنك',
          'Pay': 'الدفع',
          'Administaion': 'كلفة التوصيل',
          'Pay Date': 'تاريخ الدفع',
          'Visa': 'فيزا',
          'Feb 10,2022': 'فبراير 10,2022',
          'view map': 'رؤية الخريطة',
          'Ronald Remond': 'رونالد ريموند',
          '25 minutes on the way': 'يحتاج 25 دقيقة حتى يصل',
          'Message': 'مرسالة',
          'Notification': 'اشعارات',
          'Edit profil': 'تعديل الملف الشخصي',
          'Settings': 'الاعدادات',
          'Help & Support': 'مركز المساعدة والدعم',
          'Log out': 'تسجيل الخروج',
          'Dark Mode': 'النمط المظلم',
          'new product add to cart': 'منتج جديد قد تم اضافته الى سلة المشتريات',
          'Confirm Password*': 'تأكيد كلمة المرور',
          'Save': 'حفظ',
          'Der Mohamad': 'عزيزي محمد',
          'Do you want to save this changes ? ': 'هل تريد حفظ التغييرات ؟',
          'yes': 'نعم',
          'No': 'لا',
          'FAQ': 'أسئلة شائعة',
          'Help Center': 'مركز الدعم',
          'How I Can Bay A Product': 'كيف يمكنني شراء منتج',
          'How Long Is My Diliviery Time': 'كم يستغرق وقت التوصيل',
          'How I Can Pay For Product ': 'كيف يمكنني الدفع لشراء منتج',
          'How I Can Restore My Account': 'كيف استطيع استعادة حسابي',
          'How Made This Apllication': 'من صنع هذا التطبيق',
          'Contact us': 'تواصل معنا',
          'Chat with us': 'تواصل معنا بالرسائل',
          'You can chat with us here':
              'تستطيع التواصل معنا عن طريق الرسائل هنا',
          'Send email': 'ارسل بريدك الالكتروني',
          'Send your proplem here': 'ارسل مشكلتك هنا',
          'Customer service': 'خدمات للزبائن',
          'Call us if you need more support':
              'اتصل معنا اذا كنت تريد المزيد من الدعم',
          'This meal add to favorite ': 'هذه الوجبة قد تم اضافتها للمفضلة',
          '( 432 Reviews )': '( 432 مراجعات)',
          'Description': 'الوصف',
          'Spaicy Burger with chesse and tomato with some onion and pickled cucumber and beef meat from makdonald ':
              'برغر حار مع الجبن و الطماطم مع بعض البصل والمخلل و لحم بقري من ماكدونالد',
          'See more from\nmakdonald': 'رؤية المزيد من \nماكدونالد',
          ' Add to cart': 'اضافة الى السلة',
          'Price': 'السعر',
          'Order Completed': 'تم الطلب',
          'please give us your rate': 'اعطنا تقييمك لو سمحت',
          'Give your feedback...': 'اعطنا رأيك',
          'Send feedback': 'ارسل رأيك',
          'Thank you for send your feedback': 'شكرا لارسال رأيك',
          'Don\'t want to give us a feedback?': 'لا تريد ان تعطينا رأيك ؟',
          'Skip': 'تجاوز',
          'Delivery Details': 'تفاصيل التوصيل',
          'Waiting...': 'انتظزر',
          'Empty Cart': 'سلة المشتريات فارغة',
          'EnterNumber': 'ادخل رقم الهاتف',
          'Number*': 'رقم الهاتف',
          'The Email or Password is Wrong or This Email Not Found':
              ' او البريد الالكتروني غير موجود\n البريد الالكتروني او كلمة المرور خاطئة',
        },
        'en': {
          'start1': 'The best experience of',
          'start2': 'bying food quickly',
          'start3': 'Sign up',
          'start4': 'Login',
          'wellcome': 'Wellcome back!',
          'enterAccount': 'enter your account to use this app',
          'email': 'Email*',
          'enterEmail': 'enter your email....',
          'password': 'Password*',
          'enterPassword': 'enter your password....',
          'rememberme': 'Remember me',
          'forgetpassword': 'Forget password',
          'login': 'Login',
          'donthaveaccount': 'Don\'t have an account?',
          'signup': 'Sign Up',
          'CreateAccount': 'Create New Account',
          'Name*': 'Name*',
          'EnterName': 'enter your name....',
          'Change Language': 'Change Language ',
          'enterRegisterEmail': 'Please enter your register email',
          'we will send': 'We will send upi a verification code to your\nemail',
          'Next': 'Next',
          'we have send': 'We have sent you a verification code to your\nemail',
          'entervertificationcode': 'Please enter your verification code',
          'Vertification': 'Verification',
          'Change password': 'Change password',
          'Please enter new password': 'Please enter new password',
          'Enter new password': 'Enter new password',
          'Re-enter your password': 'Re-enter your password',
          'Finish': 'Finish',
          'Home': 'Home',
          'Search': 'Search',
          'Favorite': 'Favorite',
          'Profile': 'Profile',
          'Location': 'Location',
          'Tartous/Syria': 'Tartous/Syria',
          'Hie Mister': 'Hie Mister',
          'You have 13 discount ticket!': 'You have 13 discount ticket!',
          'Categories': 'Categories',
          'Best Sellings': 'Best Sellings',
          'See all product': 'See all product',
          'Fast Food': 'Fast Food',
          'Healthy Food': 'Healthy Food',
          'Sweet Food': 'Sweet Food',
          'Meat': 'Meat',
          'Bread': 'Bread',
          'Pizza': 'Pizza',
          'Dominoz Pizza': 'Dominoz Pizza',
          'Abo Ali resturant': 'Abo Ali resturant',
          'Fried Chicken': 'fried Chicken',
          'Cheese Burger': 'cheese Burger',
          'Makdonald': 'Makdonald',
          'Fruit Salad': 'fruit Salad',
          'Fruty': 'Fruty',
          'Donut': 'donut',
          'Donti': 'Donti',
          'Fried Potato': 'fried Potato',
          'Cart': 'Cart',
          'Total Price': 'Total Price',
          'Check Out': 'Check Out',
          'Payment': 'Payment',
          'Confirm': 'Confirm',
          'All Product': 'All Product',
          'search....': 'search....',
          'Remove all': 'Remove all',
          'Great!': 'Great!',
          'Payment Success': 'Payment Success',
          'from bank': 'from bank',
          'Pay': 'Pay',
          'Administaion': 'Administaion',
          'Pay Date': 'Pay Date',
          'Visa': 'Visa',
          'Feb 10,2022': 'Feb 10,2022',
          'view map': 'view map',
          'Ronald Remond': 'Ronald Remond',
          '25 minutes on the way': '25 minutes on the way',
          'Message': 'Message',
          'Notification': 'Notification',
          'Edit profil': 'Edit profil',
          'Settings': 'Settings',
          'Help & Support': 'Help & Support',
          'Log out': 'Log out',
          'Dark Mode': 'Dark Mode',
          'new product add to cart': 'new product add to cart',
          'Confirm Password*': 'Confirm Password*',
          'Save': 'Save',
          'Der Mohamad': 'Der Mohamad',
          'Do you want to save this changes ? ':
              'Do you want to save this changes ? ',
          'yes': 'yes',
          'No': 'No',
          'FAQ': 'FAQ',
          'Help Center': 'Help Center',
          'How I Can Bay A Product': 'How I Can Bay A Product',
          'How Long Is My Diliviery Time': 'How Long Is My Diliviery Time',
          'How I Can Pay For Product ': 'How I Can Pay For Product ',
          'How I Can Restore My Account': 'How I Can Restore My Account',
          'How Made This Apllication': 'How Made This Apllication',
          'Contact us': 'Contact us',
          'Chat with us': 'Chat with us',
          'You can chat with us here': 'You can chat with us here',
          'Send email': 'Send email',
          'Send your proplem here': 'Send your proplem here',
          'Customer service': 'Customer service',
          'Call us if you need more support':
              'Call us if you need more support',
          'This meal add to favorite ': 'This meal add to favorite ',
          '( 432 Reviews )': '( 432 Reviews )',
          'Description': 'Description',
          'Spaicy Burger with chesse and tomato with some onion and pickled cucumber and beef meat from makdonald ':
              'Spaicy Burger with chesse and tomato with some onion and pickled cucumber and beef meat from makdonald ',
          'See more from\nmakdonald': 'See more from\nmakdonald',
          ' Add to cart': ' Add to cart',
          'Price': 'Price',
          'Order Completed': 'Order Completed',
          'please give us your rate': 'please give us your rate',
          'Give your feedback...': 'Give your feedback...',
          'Send feedback': 'Send feedback',
          'Thank you for send your feedback':
              'Thank you for send your feedback',
          'Don\'t want to give us a feedback?':
              'Don\'t want to give us a feedback?',
          'Skip': 'Skip',
          'Delivery Details': 'Delivery Details',
          'Waiting...': 'Waiting...',
          'Empty Cart': 'Empty Cart',
          'EnterNumber': 'Enter phone number',
          'Number*': 'Phone Number*',
          'The Email or Password is Wrong or This Email Not Found':
              'The Email or Password is Wrong \nor This Email Not Found',
        }
      };
}
